### ISSUE TITLE
Please implement `Error` and `Display` for `ParseError`

### ISSUE THREAD

**Issue by Enyium** [WuBingzheng/primitive_fixed_point_decimal#2]
I'm using <https://crates.io/crates/anyhow> in my app to handle errors. But to be able to use `?` to convert errors into an `anyhow::Error`, the type to be converted needs to implement [`Error`](https://doc.rust-lang.org/core/error/trait.Error.html), which in turn requires the implementation of `Display`. This implementation can easily be done using <https://crates.io/crates/thiserror>.

**Comment by WuBingzheng** [comment]
done at v0.4.2

**Comment by Enyium** [comment]
`Error` still isn't implemented. This means the following code fails:

```rust
fn main() -> anyhow::Result<()> {
    println!(
        "{:?}",
        primitive_fixed_point_decimal::StaticPrecFpdec::<i8, 1>::try_from(13i8)?
        //                                                                     ^- HERE
    );

    Ok(())
}
```

...with the following error message:

```
error[E0277]: the trait bound `primitive_fixed_point_decimal::ParseError: StdError` is not satisfied
  --> src\main.rs:28:80
   |
28 |         primitive_fixed_point_decimal::StaticPrecFpdec::<i8, 1>::try_from(13i8)?
   |                                                                                ^ the trait `StdError` is not implemented for `primitive_fixed_point_decimal::ParseError`
   |
   = help: the trait `FromResidual<Result<Infallible, E>>` is implemented for `Result<T, F>`
   = note: required for `anyhow::Error` to implement `From<primitive_fixed_point_decimal::ParseError>`
   = note: required for `Result<(), anyhow::Error>` to implement `FromResidual<Result<Infallible, primitive_fixed_point_decimal::ParseError>>`
```

Note that `StdError` is just `anyhow`'s alias for `std`'s `Error` trait.

With `thiserror`, you could just do `#[derive(Error, Debug)]` or `#[derive(thiserror::Error, Debug)]`.

**Comment by WuBingzheng** [comment]
I have impl Error for ParseError at new version v0.4.3. Please check it out.
I implement it myself because I do not want to import `anyhow`. I want keep the dependency as small as possible.

**Comment by Enyium** [comment]
v0.4.3 works with error conversion into `anyhow::Error` through `?`.

The dependency in question for your crate is `thiserror`, not `anyhow`. `anyhow` is for apps (so, my code), `thiserror` is for libraries. Note that both crates are very popular in the Rust community, and are from a very active, well-known author. But, of course, that's your choice.

"too many precisions" is incorrect English. "too many" also doesn't cover the case of negative precision. Without knowing every detail about your crate's algorithms, I suppose the text from my PR - "precision out of range" - is more accurate.

**Comment by WuBingzheng** [comment]
I think v0.4.3 works for `anyhow`. I did not test it. I will test it tomorrow to make sure.

Thanks for your advice about the English. I will change it in next version. You may already find that my English is poor :(
